-- ============================================================================
-- RAG SPRINT 1 — Setup pgvector + schema base
-- ============================================================================
-- Objetivo: preparar infra de RAG (Retrieval-Augmented Generation) para
-- enriquecer prompts da IA com contexto curado (templates + cláusulas) antes
-- de chamar Claude. Reduz custo de tokens em ~60% e melhora qualidade.
--
-- Sprint 1 é APENAS schema. Nenhum embedding gerado ainda — isso vem no Sprint 2.
-- Sprint 3 plugará o retrieval em /api/ai/generate e /api/ai/review.
--
-- Embedding model planejado: Voyage AI voyage-3-lite (1024 dimensões, ótimo PT,
-- 200M tokens free tier, alinhado com recomendação oficial Anthropic).
-- ============================================================================

-- 1. Ativar extensão pgvector
create extension if not exists vector;

-- ============================================================================
-- 2. Tabela rag_templates — templates de contrato indexados
-- ============================================================================
-- Espelha contract_templates mas com embedding + campos derivados para retrieval.
-- Origem: pode ser template global Fluxrow OU template do próprio cliente
-- (organization_id != null). Modelos do cliente personalizam o RAG dele.

create table public.rag_templates (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references public.organizations(id) on delete cascade,
  -- null = template global Fluxrow (compartilhado)
  -- not null = template específico de um cliente

  source_template_id uuid references public.contract_templates(id) on delete cascade,
  -- referência ao contract_templates original (se vier de lá)

  name text not null,
  category text not null,
  content text not null,
  -- texto integral do template (markdown ou texto puro)

  content_summary text,
  -- resumo curto (1-3 parágrafos) usado para retrieval semântico mais barato

  variables jsonb default '[]'::jsonb,
  -- variáveis detectadas (ex: ["NOME_CONTRATANTE", "VALOR", ...])

  tags text[] default '{}',
  -- tags livres para filtragem (ex: ["consultoria", "honorarios"])

  embedding vector(1024),
  -- voyage-3-lite gera vetores de 1024 dim
  -- generated by indexing job in Sprint 2

  embedding_model text default 'voyage-3-lite',
  -- track which model was used, para re-embedding quando trocar de provider

  embedded_at timestamptz,
  -- when the embedding was generated

  is_active boolean default true,
  -- soft delete sem perder histórico

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index rag_templates_org_idx on public.rag_templates(organization_id);
create index rag_templates_category_idx on public.rag_templates(category);
create index rag_templates_active_idx on public.rag_templates(is_active) where is_active = true;

-- Index HNSW para retrieval semântico rápido em vector(1024)
-- m=16, ef_construction=64 — boa qualidade/performance pra escala inicial
create index rag_templates_embedding_idx on public.rag_templates
  using hnsw (embedding vector_cosine_ops)
  with (m = 16, ef_construction = 64);

-- ============================================================================
-- 3. Tabela rag_clauses — cláusulas reutilizáveis indexadas
-- ============================================================================
-- Granularidade menor que template inteiro: pega cláusulas individuais
-- (objeto, vigência, rescisão, foro, LGPD, etc.) e indexa cada uma.
-- Permite retrieval híbrido: template + cláusulas avulsas relevantes.

create table public.rag_clauses (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references public.organizations(id) on delete cascade,

  clause_type text not null,
  -- ex: 'objeto', 'vigencia', 'rescisao', 'foro', 'lgpd', 'multa', 'confidencialidade'

  title text not null,
  content text not null,

  variables jsonb default '[]'::jsonb,
  applicable_to text[] default '{}',
  -- tipos de contrato onde essa cláusula faz sentido
  -- ex: ['service_agreement', 'nda', 'rental']

  legal_basis text,
  -- citação de base legal (artigos CC, CDC, CLT, etc.)

  risk_level text check (risk_level in ('low', 'medium', 'high')),
  -- cláusulas de alto risco recebem atenção especial na revisão

  embedding vector(1024),
  embedding_model text default 'voyage-3-lite',
  embedded_at timestamptz,

  is_active boolean default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index rag_clauses_org_idx on public.rag_clauses(organization_id);
create index rag_clauses_type_idx on public.rag_clauses(clause_type);
create index rag_clauses_active_idx on public.rag_clauses(is_active) where is_active = true;

create index rag_clauses_embedding_idx on public.rag_clauses
  using hnsw (embedding vector_cosine_ops)
  with (m = 16, ef_construction = 64);

-- ============================================================================
-- 4. Tabela rag_query_cache — cache de respostas para queries idênticas
-- ============================================================================
-- Se o mesmo input chega 2x em 7 dias, reusa resultado sem chamar Claude.
-- Economia adicional de tokens. Hash SHA-256 do input normalizado.

create table public.rag_query_cache (
  cache_key text primary key,
  -- sha256(normalized_input)

  query_text text not null,
  query_embedding vector(1024),

  retrieval_template_ids uuid[] default '{}',
  retrieval_clause_ids uuid[] default '{}',
  -- quais templates/clausulas foram recuperados

  llm_response jsonb not null,
  llm_model text not null,
  -- ex: 'claude-sonnet-4-6'

  tokens_input int,
  tokens_output int,
  -- contabilizar economia

  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '7 days')
);

create index rag_query_cache_expires_idx on public.rag_query_cache(expires_at);

-- ============================================================================
-- 5. Função de retrieval — top-k templates similares
-- ============================================================================
create or replace function public.rag_match_templates(
  query_embedding vector(1024),
  match_threshold float default 0.7,
  match_count int default 5,
  filter_org_id uuid default null,
  filter_category text default null
)
returns table (
  id uuid,
  name text,
  category text,
  content text,
  content_summary text,
  variables jsonb,
  similarity float
)
language sql stable as $$
  select
    rt.id,
    rt.name,
    rt.category,
    rt.content,
    rt.content_summary,
    rt.variables,
    1 - (rt.embedding <=> query_embedding) as similarity
  from public.rag_templates rt
  where
    rt.is_active = true
    and rt.embedding is not null
    and (filter_org_id is null or rt.organization_id = filter_org_id or rt.organization_id is null)
    -- inclui templates globais (organization_id null) + templates do org filtrado
    and (filter_category is null or rt.category = filter_category)
    and (1 - (rt.embedding <=> query_embedding)) > match_threshold
  order by rt.embedding <=> query_embedding
  limit match_count;
$$;

-- ============================================================================
-- 6. Função de retrieval — top-k cláusulas similares
-- ============================================================================
create or replace function public.rag_match_clauses(
  query_embedding vector(1024),
  match_threshold float default 0.65,
  match_count int default 8,
  filter_org_id uuid default null,
  filter_clause_type text default null
)
returns table (
  id uuid,
  clause_type text,
  title text,
  content text,
  legal_basis text,
  risk_level text,
  similarity float
)
language sql stable as $$
  select
    rc.id,
    rc.clause_type,
    rc.title,
    rc.content,
    rc.legal_basis,
    rc.risk_level,
    1 - (rc.embedding <=> query_embedding) as similarity
  from public.rag_clauses rc
  where
    rc.is_active = true
    and rc.embedding is not null
    and (filter_org_id is null or rc.organization_id = filter_org_id or rc.organization_id is null)
    and (filter_clause_type is null or rc.clause_type = filter_clause_type)
    and (1 - (rc.embedding <=> query_embedding)) > match_threshold
  order by rc.embedding <=> query_embedding
  limit match_count;
$$;

-- ============================================================================
-- 7. RLS — Row Level Security
-- ============================================================================
-- Templates globais (organization_id null) são visíveis para todos os autenticados.
-- Templates de cliente só são visíveis para membros daquela org.
-- Service role bypassa RLS (usado pela API server-side).

alter table public.rag_templates enable row level security;
alter table public.rag_clauses enable row level security;
alter table public.rag_query_cache enable row level security;

-- Templates: leitura
create policy "rag_templates_select"
  on public.rag_templates for select
  to authenticated
  using (
    organization_id is null  -- global
    or organization_id in (
      select organization_id from public.memberships where user_id = auth.uid()
    )
  );

-- Cláusulas: leitura
create policy "rag_clauses_select"
  on public.rag_clauses for select
  to authenticated
  using (
    organization_id is null
    or organization_id in (
      select organization_id from public.memberships where user_id = auth.uid()
    )
  );

-- Cache: apenas service role escreve/lê (não exposto ao client)
-- (deny all para authenticated; service role bypassa)

-- ============================================================================
-- 8. Trigger de updated_at
-- ============================================================================
create or replace function public.trigger_set_timestamp()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger rag_templates_set_timestamp
  before update on public.rag_templates
  for each row execute function public.trigger_set_timestamp();

create trigger rag_clauses_set_timestamp
  before update on public.rag_clauses
  for each row execute function public.trigger_set_timestamp();

-- ============================================================================
-- 9. Comentários de documentação
-- ============================================================================
comment on table public.rag_templates is
  'Templates de contrato indexados para RAG. Sprint 1: schema apenas. Sprint 2 popula embeddings.';
comment on table public.rag_clauses is
  'Cláusulas reutilizáveis indexadas para retrieval granular. Permite compor contratos via mix de clauses.';
comment on table public.rag_query_cache is
  'Cache de respostas LLM por hash do input. TTL 7 dias. Reduz custo em ~30% adicional.';
comment on function public.rag_match_templates is
  'Retrieval top-k templates por similaridade cosseno. Aceita filtro por org + categoria.';
comment on function public.rag_match_clauses is
  'Retrieval top-k cláusulas por similaridade cosseno. Aceita filtro por org + tipo.';
